/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.henrys.grocery;

public class Store {
    public String getGreeting() {
        return "Welcome, please enter product and quantity";
    }

    public static void main(String[] args) {
        System.out.println(new Store().getGreeting());
    }
}
